version: "3.8"
services:
  api:
    build:
      context: ./johome-api
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    ports:
      - 1337:1337
    environment:
      - HOST=api
      - PORT=1337
      - APP_KEYS=RHd34RsXrf8FbsAw2tAJzQ==,nH6hQq6Gq4kcI8rP4CtRaQ==,r71vT/30e0NdIUbsuoVnSA==,FSnyTHMnANwvTIdB8ggVIQ==
      - API_TOKEN_SALT=Xn18rLgDs7YzRIJtenjBOA==
      - ADMIN_JWT_SECRET=+EK7ntdITlU4JJZLq0R+YQ==
      - JWT_SECRET=7Ivbynvl2fmxcgP+spjTPA==
      - URL=https://johome.site/strapi/
      - CLOUDINARY_NAME=dyotzt92h
      - CLOUDINARY_API_KEY=875263122291697
      - CLOUDINARY_API_SECRET=2iu-Vvr4h5lnM_bjBL3Hco7nu9w
  web:
    build:
      context: ./johome-web
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 3000:3000
    environment:
      - CLOUDINARY_NAME=dyotzt92h
      - CLOUDINARY_API_KEY=875263122291697
      - CLOUDINARY_API_SECRET=2iu-Vvr4h5lnM_bjBL3Hco7nu9w
    depends_on:
      - api
    volumes:
      - web
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/
      - ./certbot/conf/:/etc/letsencrypt/
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf.d/:/etc/nginx/conf.d/
      - ./certbot/www:/var/www/certbot/
      - ./certbot/conf/:/etc/nginx/ssl/
    depends_on:
      - web
      - api
      - certbot
volumes:
  web: